# This file was generated by GoReleaser. DO NOT EDIT.
cask "trackyou" do
  version "0.8.8"

  on_macos do
    on_intel do
      sha256 "df503e75934d38da96c781732f1ffd2af2f3677a83b9ef93ce0e45cab865880c"
      url "https://github.com/pasmon/trackyou/releases/download/v#{version}/trackyou_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8d25a305bb6cb4c03b376fb00475733d0c0972d9c11c8e6a79071b1048737e74"
      url "https://github.com/pasmon/trackyou/releases/download/v#{version}/trackyou_Darwin_arm64.tar.gz"
    end
  end

  name "trackyou"
  desc "Cross-platform desktop time tracker built with Go and Fyne"
  homepage "https://github.com/pasmon/trackyou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trackyou"

  # No zap stanza required

end
