# This file was generated by GoReleaser. DO NOT EDIT.
cask "trackyou" do
  version "0.8.3"

  on_macos do
    on_intel do
      sha256 "e63e0b5f1cba5c47ea3fa28a3bf2add11d0f5ed76ea6f58459fb9498984c3f1b"
      url "https://github.com/pasmon/trackyou/releases/download/v#{version}/trackyou_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "aed40b15341c3ee582c398cadf9d2bf0854dc870c9b89f7cdaa6498cbe359918"
      url "https://github.com/pasmon/trackyou/releases/download/v#{version}/trackyou_Darwin_arm64.tar.gz"
    end
  end

  name "trackyou"
  desc "Cross-platform desktop time tracker built with Go and Fyne"
  homepage "https://github.com/pasmon/trackyou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trackyou"

  # No zap stanza required

end
