# This file was generated by GoReleaser. DO NOT EDIT.
cask "trackyou" do
  version "0.8.6"

  on_macos do
    on_intel do
      sha256 "c2e05229f4206ad056703cfef5ed2a493aed360fdbc3c84210f7b5357f352687"
      url "https://github.com/pasmon/trackyou/releases/download/v#{version}/trackyou_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "706344d3a935332dfae005395b169a3edfb7fd9364920948f2bf37a08048509b"
      url "https://github.com/pasmon/trackyou/releases/download/v#{version}/trackyou_Darwin_arm64.tar.gz"
    end
  end

  name "trackyou"
  desc "Cross-platform desktop time tracker built with Go and Fyne"
  homepage "https://github.com/pasmon/trackyou"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "trackyou"

  # No zap stanza required

end
